name: CI with Gradle

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Allow Gradlew execution
        run: chmod +x gradlew
      - name: Build and test
        run: ./gradlew build test
        env:
          RUNNER: github